dentist_index:
    path:     /
    defaults: { _controller: "MedicalBundle:Dentist:index" }
    methods:  GET

dentist_show:
    path:     /{id}/show
    defaults: { _controller: "MedicalBundle:Dentist:show" }
    methods:  GET

dentist_new:
    path:     /new
    defaults: { _controller: "MedicalBundle:Dentist:new" }
    methods:  [GET, POST]

dentist_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicalBundle:Dentist:edit" }
    methods:  [GET, POST]

dentist_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicalBundle:Dentist:delete" }
    methods:  DELETE
