others_index:
    path:     /
    defaults: { _controller: "MedicalBundle:Others:index" }
    methods:  GET

others_show:
    path:     /{id}/show
    defaults: { _controller: "MedicalBundle:Others:show" }
    methods:  GET

others_new:
    path:     /new
    defaults: { _controller: "MedicalBundle:Others:new" }
    methods:  [GET, POST]

others_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicalBundle:Others:edit" }
    methods:  [GET, POST]

others_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicalBundle:Others:delete" }
    methods:  DELETE
