# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
#                check_path: fos_user_security_check
#                default_target_path: /
#                success_handler: redirect.after.login
            logout:       true
            anonymous:    true

#
#            logout:
#                path: fos_user_security_logout
#                target: /
                # [redirection apres logout]
#                success_handler: redirect.after.logout

    access_control:
        - { path: ^/?$, role: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: ROLE_ADMIN }
        - { path: ^/setting, role: ROLE_USER }
        - { path: ^/information, role: ROLE_USER }
        - { path: ^/familly, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }


