# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # [...] HealthBundle/Service
      upload.service:
          class: src\HealthBundle\Services\UploadsService
          arguments: ['@service_container']

      app.form.registration:
              class: UserBundle\Form\UserType
              tags:
                  - { name: form.type, alias: app_user_registration }
