<?php

namespace HealthBundle\Repository;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamillyRepository extends \Doctrine\ORM\EntityRepository
{
}
