<?php

namespace InformationBundle\Repository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{
//    public function findIdDoctor($information_id)
//    {
////        Alias 's' = class searchrepository
////        Alias 'c' = categorie
//
//        $repository = $this->getDoctrine()->getRepository('HealthBundle:Information');
//
//        $qb = $repository->createQueryBuilder('p')
//            ->select('p.id, c.information_d')
//            ->join('p.information', 'c')
//            ->where('p.id = c.information_id');
//
//        return $qb->getQuery()->getResult();
//    }
}
