<?php

namespace MedicalBundle\Repository;

/**
 * DentistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DentistRepository extends \Doctrine\ORM\EntityRepository
{
}
