<?php

namespace MedicalBundle\Repository;

/**
 * InsuranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsuranceRepository extends \Doctrine\ORM\EntityRepository
{
}
