<?php

namespace MedicalBundle\Repository;

/**
 * OthersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OthersRepository extends \Doctrine\ORM\EntityRepository
{
}
