<?php

namespace MedicalBundle\Repository;

/**
 * VaccinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VaccinesRepository extends \Doctrine\ORM\EntityRepository
{
}
