<?php

namespace MedicalBundle\Repository;

/**
 * XraysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XraysRepository extends \Doctrine\ORM\EntityRepository
{
}
