AppointmentBundle\Entity\Appointment:
    type: entity
    table: null
    repositoryClass: AppointmentBundle\Repository\AppointmentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        date:
            type: string
            length: 255
            nullable: true
        action:
            type: string
            length: 255

    manyToOne:
            dentist:
                targetEntity: MedicalBundle\Entity\Dentist
            insurance:
                targetEntity: MedicalBundle\Entity\Insurance
            medication:
                targetEntity: MedicalBundle\Entity\Medication
            other:
                targetEntity: MedicalBundle\Entity\Others
            vaccines:
                targetEntity: MedicalBundle\Entity\Vaccines
            xray:
                targetEntity: MedicalBundle\Entity\Xrays

    lifecycleCallbacks: {  }